### ISSUE TITLE
New R package for astronomy

### ISSUE THREAD

**Issue by uskovgs** [hwborchers/zaRastro#2]
@hwborchers 

I would like to share with you the new astronomy package ![panstarrs](https://cran.r-project.org/web/packages/panstarrs). It is an interface to the API for 'Pan-STARRS1'.
https://cran.r-project.org/web/packages/panstarrs/

**Comment by hwborchers** [comment]
Thanks for pointing this out.
I know I have to update this repository, check all the links to packages, etc.
I am also looking for a database of stars that can w/o a hassle be used to generate, e.g., a Hertzsprung-Russel diagram.
All the data sources I found are much too complicated for such a simple purpose.
